language: c++
addons:
  apt:
    sources:
      - sourceline: deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64 /
        key_url: http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/7fa2af80.pub
    packages:
      - cmake
      - ninja-build
      - libopencv-dev
      - libfftw3-dev
      - cuda-command-line-tools-8-0 cuda-cufft-dev-8-0
env:
  - CUDA_BIN_PATH=/usr/local/cuda-8.0
script: make
